Perf test/virtual avx2
chriseclectic/qiskit-aer pull request #11
Opened 2020-10-01 20:19 UTC by vvilpas

### Summary

### Details and comments

2020-10-01 21:16 UTC, chriseclectic requested changes
If performance isn't lost by using virtual function calls this makes it easier to place inside qubit vector.

You can also make all the previously static member functions of the transformer `const`.

2020-10-01 21:16 UTC, chriseclectic commented on src/simulators/statevector/transformer.hpp
>                             const reg_t &qubits, const cvector_t<double> &mat);
If these methods are no-longer static, we can make them const:
```suggestion
                           const reg_t &qubits, const cvector_t<double> &mat) const;
```

2020-10-01 21:16 UTC, chriseclectic commented on src/simulators/statevector/transformer.hpp
>                               const reg_t &qubits, const cvector_t<double> &mat);
```suggestion
                             const reg_t &qubits, const cvector_t<double> &mat) const;
```

2020-10-01 21:16 UTC, chriseclectic commented on src/simulators/statevector/transformer_avx2.hpp
>                             const reg_t &qubits, const cvector_t<double> &mat);
```suggestion
                           const reg_t &qubits, const cvector_t<double> &mat) const override;
```

2020-10-02 09:09 UTC, vvilpas commented
Are we using these classes (or planning to use them)  for non-complex numbers? If only for complex numbers we can get rid of `container` as a template parameter.

2020-10-02 14:38 UTC, chriseclectic commented
I was leaving it there so in principle you could use it for other container types (like Vector, std::vector, std::array), but not sure the AVX2 code would work without modification for those other classes yet (you would have to modify it to call `container.data()` to get the pointer.

2020-10-02 14:39 UTC, chriseclectic approved these changes

2020-10-02 14:39 UTC, merged